# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - doronin.ltd@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="75827445-32dd-41cb-b567-2bf22633ff40"

jdk:
  - openjdk12

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U tracker

addons:
  postgresql: "12.2"